# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goarch:
    - amd64
  goarm:
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  name_template: "{{.ProjectName}}-{{.Env.USER}}"
brews:
  - github:
      owner: codechenx
      name: homebrew-test
    commit_author:
      name: codechenx
      email: codechenx@gmail.com
    description: "just a"
    homepage: "just a test"
nfpms:
  - maintainer: codechenx
    license: Apache 2.0
    formats:
        - deb
        - rpm
    bindir: /usr/bin